pipeline 
{
    agent 
    {
        docker { image 'python:3.6.10' } 
    }
    stages 
    {
        stage('build_project') 
        {
            steps 
            {
                sh 'python3 --version'
                sh 'python3 -m pip install robotframework'
                sh 'robot --version'
            }
        }
        stage('func_test')
        {
            steps
            {
                sh 'robot pipline/my.rst' 
            }
        }
    }
}
