pipeline {
    agent { docker { image 'python:3.6.10' } }
    stages {
        stage('build') {
            steps {
                sh 'ls'
                sh 'python3 main.py'
            }
        }
    }
}
